### ISSUE TITLE
Integrate with Spark

### ISSUE THREAD

**Issue by eleansa** [ScalaConnoisseurs/PoliceSpark#5]
Query Cassandra and push data to Spark for analysis

**Comment by JosephGoulden** [comment]
I think we should integrated Spark with the websocket, so that we can do all of the analysis realtime. Like in my pull request.. https://github.com/ScalaConnoisseurs/PoliceSpark/pull/7

**Comment by eleansa** [comment]
Ok, that sounds a good idea. Let's discuss with the guys and create more substantial stories.
